BUILDER      = ba build
TRAINER      = ba train
TRAINER_OPTS = --no-browser --debug
AGENTID      = go-bytearena-example-simple

build:
	$(BUILDER)

run: build
	$(TRAINER) --agent $(AGENTID) $(TRAINER_OPTS)
